name: 'build-test'
on: # rebuild any PRs and main branch changes
  push:
    branches:
      - main

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - name: Get the sources
        uses: actions/checkout@v1
      - name: Restore the dependencies
        run: npm ci
      - name: Build
        run: npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - name: Get the sources
        uses: actions/checkout@v1
      - name: Create a release draft for a version tag
        id: create-release-draft
        uses: ./
      - name: Print the URL of the release draft
        run: echo ${{ steps.create-release-draft.outputs.release-url }}
